name: Deploy Laravel via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: ${{ secrets.PATH }}
          local-dir: "./"

      - name: Clear Laravel Cache
        run: |
          curl "${{ secrets.WEBSITE_URL }}/artisan.php?cmd=cache:clear"
